# Generated by Django 4.2.25 on 2026-02-11 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_message_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_id', models.PositiveBigIntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='app.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_read_states',
                'unique_together': {('user', 'channel')},
            },
        ),
    ]
