# Generated by Django 4.2.25 on 2026-02-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
