# Generated by Django 4.2.25 on 2026-02-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_status_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='icon',
            field=models.ImageField(blank=True, default='', upload_to='server_icons/'),
        ),
    ]
