# Generated by Django 4.2.25 on 2026-02-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_server_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
