# Generated by Django 4.2.25 on 2026-02-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_server_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='attachment',
            field=models.FileField(blank=True, default='', upload_to='dm_attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', '图片'), ('video', '视频'), ('audio', '音频'), ('file', '文件')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, default='', upload_to='attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', '图片'), ('video', '视频'), ('audio', '音频'), ('file', '文件')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
